//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libreriaEntities : DbContext
    {
        public libreriaEntities()
            : base("name=libreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<estadousuario> estadousuario { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<prestamo> prestamo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<View_autor_libro> View_autor_libro { get; set; }
        public virtual DbSet<View_usuario_estado_libro_prestamo> View_usuario_estado_libro_prestamo { get; set; }
    }
}
