//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public int idprestamo { get; set; }
        public int idLibro { get; set; }
        public int idusuario { get; set; }
        public System.DateTime fechaprestamo { get; set; }
        public System.DateTime fechadevo { get; set; }
        public int ndias { get; set; }
        public string observacion { get; set; }
    
        public virtual libro libro { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
