//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int idusuario { get; set; }
        public int idestadousuario { get; set; }
        public int edadusuario { get; set; }
        public string apelusuario { get; set; }
        public string nomusuario { get; set; }
        public int telusuario { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaingreso { get; set; }
    
        public virtual estadousuario estadousuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
