//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_usuario_estado_libro_prestamo
    {
        public string nomusuario { get; set; }
        public int telusuario { get; set; }
        public string estadousuario { get; set; }
        public string titulolibro { get; set; }
        public int ndias { get; set; }
        public System.DateTime fechaprestamo { get; set; }
        public System.DateTime fechadevo { get; set; }
        public string observacion { get; set; }
    }
}
