//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_autor_libro
    {
        public string nombreautor { get; set; }
        public string titulolibro { get; set; }
        public string editorial { get; set; }
        public int año { get; set; }
        public int existencia { get; set; }
    }
}
